# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  reuse:
    runs-on: ubuntu-24.04
    container: fsfe/reuse:4

    steps:
      - uses: actions/checkout@v4
      
      - name: Run reuse
        run: reuse lint

  build:
    runs-on: ubuntu-24.04
    container: alcarazzam/kde

    steps:
      - uses: actions/checkout@v4

      - name: Configure project
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build build --parallel

